# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_auto_20180304_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaoheyuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaoheyuan', to=settings.AUTH_USER_MODEL)),
                ('yuangong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuangong', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='20XX年 - X 周 - (月/日 - 月/日)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rule',
            name='details',
            field=models.TextField(verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='考核简述'),
        ),
    ]
