# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180305_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaoherecord',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
