# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_kaoherecord_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kaoherecord',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='weekstat',
            name='name',
            field=models.CharField(default='20XX年-X周/X月', max_length=100, verbose_name='20XX年-X周/X月'),
        ),
    ]
