# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import erp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('HONGDA', '宏大'), ('OUT', '外购'), ('CLIENT', '客户提供')], default='HONGDA', max_length=20)),
                ('product', models.CharField(choices=[('BAND', '拉力带'), ('POWERBAND', '208圈'), ('101BAND', '101圈'), ('MINIBAND', '小圈(101以下)'), ('OLDLATEX', '老产品'), ('BALLOON', '气球'), ('CARTON', '外箱'), ('BOX', '彩盒'), ('BAG', '网袋/编织袋'), ('OPP', 'OPP/EPP袋'), ('STICK', '贴标'), ('VALVE', '前阀/尾阀'), ('OTHER', '其他')], max_length=100)),
                ('specs', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=erp.models.item_logo_upload_to)),
                ('status', models.CharField(default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jihuadan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('deliver_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscribeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('BAND', '拉力带'), ('POWERBAND', '208圈'), ('101BAND', '101圈'), ('MINIBAND', '小圈(101以下)'), ('OLDLATEX', '老产品'), ('BALLOON', '气球'), ('CARTON', '外箱'), ('BOX', '彩盒'), ('BAG', '网袋/编织袋'), ('OPP', 'OPP/EPP袋'), ('STICK', '贴标'), ('VALVE', '前阀/尾阀'), ('OTHER', '其他')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='jihuadan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Jihuadan'),
        ),
    ]
