# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import erp.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('HONGDA', '宏大'), ('OUT', '外购'), ('CLIENT', '客户提供')], default='HONGDA', max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('specs', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=erp.models.item_logo_upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='jihuadan',
            name='deliver_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jihuadan',
            name='status',
            field=models.CharField(default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='jihuadan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Jihuadan'),
        ),
    ]
