# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20180122_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.CharField(choices=[('BAND', '拉力带'), ('POWERBAND', '208圈'), ('101BAND', '101圈'), ('MINIBAND', '小圈(101以下)'), ('OLDLATEX', '老产品'), ('BALLOON', '气球'), ('CARTON', '外箱'), ('BOX', '彩盒'), ('BAG', '网袋/编织袋'), ('OPP', 'OPP/EPP袋'), ('STICK', '贴标'), ('VALVE', '前阀/尾阀'), ('OTHER', '其他')], max_length=100),
        ),
    ]
