# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20180122_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='DRAFT', max_length=10),
        ),
    ]
