# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0004_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='status2',
            field=models.CharField(default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='itemlog',
            name='jhditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Item'),
        ),
        migrations.AddField(
            model_name='itemlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
