# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20180123_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlog',
            old_name='jhditem',
            new_name='item',
        ),
    ]
