# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0006_auto_20180123_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('BAND', '拉力带'), ('POWERBAND', '208圈'), ('101BAND', '101圈'), ('MINIBAND', '小圈(101以下)'), ('OLDLATEX', '老产品'), ('BALLOON', '气球'), ('CARTON', '外箱'), ('BOX', '彩盒'), ('BAG', '网袋/编织袋'), ('OPP', 'OPP/EPP袋'), ('STICK', '贴标'), ('VALVE', '前阀/尾阀'), ('OTHER', '其他')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
