# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_remove_item_status2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jihuadan',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
