# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import erp_simple.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouquanLiuchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('shengchan_riqi', models.DateField(default=erp_simple.models.get_next_day, verbose_name='生产日期')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, '常规货'), (2, '迪卡侬')], default=1, verbose_name='分类')),
                ('line', models.PositiveIntegerField(verbose_name='制作线')),
                ('caozuogong', models.CharField(max_length=50, verbose_name='操作工')),
                ('fuzhugong', models.CharField(max_length=50, verbose_name='辅助工')),
                ('jihuadan', models.CharField(blank=True, max_length=10, null=True, verbose_name='订单号')),
                ('color', models.CharField(max_length=10, verbose_name='颜色')),
                ('jihua_dapian', models.PositiveIntegerField(default=0, verbose_name='计划大片数')),
                ('shiji_dapian', models.PositiveIntegerField(default=0, verbose_name='实际大片数')),
                ('is_delete', models.BooleanField(choices=[(False, '有效流程单'), (True, '无效流程单')], default=False, verbose_name='已经删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Jhd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=erp_simple.models.jihuadan_upload_to)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jhd_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=erp_simple.models.jihuadan_file_upload_to)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('jhd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_simple.Jhd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Jhd_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('jhd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_simple.Jhd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
