# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erp_simple', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jhd_file',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='jhd_log',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='jhd_file',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 24, 14, 49, 53, 923084, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
