# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import erp_simple.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp_simple', '0002_auto_20180224_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouquanLiuchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('jihuadan', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, '常规货'), (2, '迪卡侬')], default=1)),
                ('line', models.PositiveIntegerField()),
                ('worker', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('jihua_dapian', models.PositiveIntegerField(default=0)),
                ('shiji_dapian', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(default=erp_simple.models.get_next_day)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
