# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_simple', '0003_houquanliuchen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houquanliuchen',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='houquanliuchen',
            name='is_delete',
            field=models.BooleanField(choices=[(False, '有效流程单'), (True, '无效流程单')], default=False),
        ),
    ]
