# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import erp_simple.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_simple', '0004_auto_20180227_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houquanliuchen',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='houquanliuchen',
            name='worker',
        ),
        migrations.AddField(
            model_name='houquanliuchen',
            name='caozuogong',
            field=models.CharField(default=1, max_length=50, verbose_name='操作工'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houquanliuchen',
            name='fuzhugong',
            field=models.CharField(default=0, max_length=50, verbose_name='辅助工'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houquanliuchen',
            name='shengchan_riqi',
            field=models.DateField(default=erp_simple.models.get_next_day, verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='houquanliuchen',
            name='color',
            field=models.CharField(max_length=10, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='houquanliuchen',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, '常规货'), (2, '迪卡侬')], default=1, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='houquanliuchen',
            name='is_delete',
            field=models.BooleanField(choices=[(False, '有效流程单'), (True, '无效流程单')], default=False, verbose_name='已经删除'),
        ),
        migrations.AlterField(
            model_name='houquanliuchen',
            name='jihua_dapian',
            field=models.PositiveIntegerField(default=0, verbose_name='计划大片数'),
        ),
        migrations.AlterField(
            model_name='houquanliuchen',
            name='jihuadan',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='houquanliuchen',
            name='line',
            field=models.PositiveIntegerField(verbose_name='制作线'),
        ),
        migrations.AlterField(
            model_name='houquanliuchen',
            name='shiji_dapian',
            field=models.PositiveIntegerField(default=0, verbose_name='实际大片数'),
        ),
    ]
