# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 15:57
from __future__ import unicode_literals

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=200, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('source', models.IntegerField(choices=[(0, '老客户'), (1, '1688询盘'), (2, 'Alibaba询盘'), (3, 'Alibaba RFQ'), (4, '客人联系我们'), (5, '网上发掘的客户信息'), (6, '展会联系'), (7, '其他渠道'), (8, '2018 Taispo 展会')], default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '潜在客人'), (2, '进展中的客人'), (3, '重要的客人'), (4, '有问题的客人')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500, verbose_name='说明')),
                ('file', models.FileField(upload_to=crm.models.client_file_upload_to, verbose_name='文件')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=crm.models.client_log_file_upload_to)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('address', models.TextField(blank=True, default='N/A', verbose_name='地址')),
                ('namecard_front', models.ImageField(blank=True, null=True, upload_to=crm.models.namecard_upload_to, verbose_name='名片正面')),
                ('namecard_back', models.ImageField(blank=True, null=True, upload_to=crm.models.namecard_upload_to, verbose_name='名片反面')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMIT', '提交'), ('DELETE', '取消'), ('SEND', '发货'), ('COMPLETE', '完成')], default='DRAFT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='订单金额', max_digits=10)),
                ('currency', models.CharField(choices=[('RMB', 'RMB'), ('USD', 'USD')], default='RMB', max_length=5)),
                ('trueAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('externalID', models.CharField(default='N/A', help_text='客户订单号', max_length=50)),
                ('internalID', models.CharField(help_text='内部跟踪号', max_length=20, unique=True)),
                ('contract', models.FileField(upload_to=crm.models.contact_upload_to)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contactor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
