# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 14:48
from __future__ import unicode_literals

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20171226_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT')], default='DRAFT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='订单金额', max_digits=10)),
                ('currency', models.CharField(choices=[('RMB', 'RMB'), ('USD', 'USD')], default='RMB', max_length=5)),
                ('trueAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orderID', models.CharField(help_text='订单号', max_length=20, unique=True)),
                ('contract', models.FileField(upload_to=crm.models.contact_upload_to)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
                ('contactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contactor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
