# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesID',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMIT', '提交'), ('DELETE', '取消'), ('SEND', '发货'), ('COMPLETE', '完成')], default='DRAFT', max_length=10),
        ),
    ]
