# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20171227_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='salesID',
        ),
    ]
