# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_order_salesid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderID',
        ),
        migrations.AddField(
            model_name='order',
            name='externalID',
            field=models.CharField(default='', help_text='客户订单号', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='internalID',
            field=models.CharField(default='', help_text='内部跟踪号', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
