# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 15:02
from __future__ import unicode_literals

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_auto_20180123_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('file', models.FileField(blank=True, upload_to=crm.models.client_file_upload_to)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('next_date', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client'),
        ),
        migrations.AddField(
            model_name='clientlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
