# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 15:11
from __future__ import unicode_literals

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180225_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=crm.models.client_file_upload_to),
        ),
        migrations.AlterField(
            model_name='clientlog',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
