# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20180225_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='star',
        ),
        migrations.AddField(
            model_name='client',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (1, 2)], default=1),
        ),
    ]
