# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180225_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[('潜在客人', 1), ('进展中的客人', 2), ('重要的客人', 3), ('有问题的客人', 4)], default=1),
        ),
    ]
