# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20180225_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.IntegerField(choices=[(0, '老客户'), (1, '1688询盘'), (2, 'Alibaba询盘'), (3, 'Alibaba RFQ'), (4, '客人联系我们'), (5, '网上发掘的客户信息'), (6, '展会联系'), (7, '其他渠道')], default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '潜在客人'), (2, '进展中的客人'), (3, '重要的客人'), (4, '有问题的客人')], default=1),
        ),
    ]
