# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180226_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 28, 17, 47, 1, 347922, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
