# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 16:12
from __future__ import unicode_literals

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatelogGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='分类名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalog.models.catelog_image_uploadto, verbose_name='图片')),
                ('description', models.TextField(verbose_name='说明')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='名称')),
                ('frontimage', models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_uploadto, verbose_name='正面图片')),
                ('sideimage', models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_uploadto, verbose_name='侧面图片')),
                ('weight', models.IntegerField(verbose_name='重量(g)')),
                ('size', models.CharField(max_length=100, verbose_name='尺寸')),
                ('material', models.CharField(max_length=100, verbose_name='材质')),
                ('note', models.TextField(blank=True, null=True, verbose_name='其他说明')),
                ('catelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CatelogGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
