# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 16:20
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateloggroup',
            name='image',
            field=models.ImageField(default=0, upload_to=catalog.models.catelog_image_uploadto, verbose_name='图片'),
            preserve_default=False,
        ),
    ]
