# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180315_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('unitcost', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='单价(CNY)')),
                ('moq', models.IntegerField(default=0, verbose_name='最少起订量')),
                ('note', models.TextField(verbose_name='其他信息')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='suggestmoq',
            field=models.IntegerField(default=0, verbose_name='建议最少起订量'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggestprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='建议销售价格(RMB)'),
        ),
        migrations.AddField(
            model_name='productsource',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='产品'),
        ),
    ]
