# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_itemphoto_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='MOQ',
            field=models.IntegerField(blank=True, default=0, help_text='最小起订量'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='cartongw',
            field=models.IntegerField(blank=True, default=0, help_text='毛重'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='cartonsize',
            field=models.CharField(blank=True, default=0, help_text='装箱外箱尺寸', max_length=50),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='qtypercarton',
            field=models.IntegerField(blank=True, default=0, help_text='每箱的数量'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='unitprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='weight',
            field=models.IntegerField(blank=True, default=0, help_text='克重'),
        ),
    ]
