# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 13:18
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180315_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateloggroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productsource',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frontimage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sideimage',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_uploadto, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catelog',
            field=models.CharField(max_length=300, verbose_name='产品分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(default='N/A', max_length=100, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='N/A', max_length=100, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='重量(g)'),
        ),
        migrations.DeleteModel(
            name='CatelogGroup',
        ),
        migrations.DeleteModel(
            name='ProductSource',
        ),
    ]
