# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171226_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitemsupplier',
            name='moq',
            field=models.IntegerField(default=0, help_text='最小起订量'),
        ),
    ]
