# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171226_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='cartongw',
            field=models.DecimalField(decimal_places=2, default=0, help_text='毛重', max_digits=8),
        ),
    ]
