# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
            preserve_default=False,
        ),
    ]
