# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productlog_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='成本价格'),
        ),
    ]
