# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 14:10
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_costprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_uploadto, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='log',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='记录'),
        ),
    ]
