# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 14:19
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180322_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_log_image_uploadto, verbose_name='图片'),
        ),
    ]
